// <auto-generated />
using System;
using CraftAi.Modules.Organizations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftAi.Modules.Organizations.Persistence.Migrations
{
    [DbContext(typeof(OrganizationsDbContext))]
    [Migration("20260911115006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizations")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.HasKey("Id")
                        .HasName("pk_academic_years");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_academic_years_organization_id");

                    b.ToTable("academic_years", "organizations");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.ClassGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_year_id");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("letter");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_class_groups");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_class_groups_academic_year_id");

                    b.HasIndex("OrganizationId", "AcademicYearId", "Grade", "Letter")
                        .IsUnique()
                        .HasDatabaseName("ix_class_groups_organization_id_academic_year_id_grade_letter");

                    b.ToTable("class_groups", "organizations");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_organizations_name");

                    b.ToTable("organizations", "organizations");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_group_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("external_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_members");

                    b.HasIndex("ClassGroupId")
                        .HasDatabaseName("ix_organization_members_class_group_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_user_id");

                    b.HasIndex("OrganizationId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_organization_id_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "Role")
                        .HasDatabaseName("ix_organization_members_organization_id_role");

                    b.ToTable("organization_members", "organizations");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.UserImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreviewJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preview_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_import_batches");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_user_import_batches_organization_id");

                    b.ToTable("user_import_batches", "organizations");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.AcademicYear", b =>
                {
                    b.HasOne("CraftAi.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_years_organizations_organization_id");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.ClassGroup", b =>
                {
                    b.HasOne("CraftAi.Modules.Organizations.Domain.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_groups_academic_years_academic_year_id");

                    b.HasOne("CraftAi.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_groups_organizations_organization_id");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.OrganizationMember", b =>
                {
                    b.HasOne("CraftAi.Modules.Organizations.Domain.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organization_members_class_groups_class_group_id");

                    b.HasOne("CraftAi.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organizations_organization_id");
                });

            modelBuilder.Entity("CraftAi.Modules.Organizations.Domain.UserImportBatch", b =>
                {
                    b.HasOne("CraftAi.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_import_batches_organizations_organization_id");
                });
#pragma warning restore 612, 618
        }
    }
}
