// <auto-generated />
using System;
using CraftAi.Modules.Content.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftAi.Modules.Content.Persistence.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_lessons_section_id");

                    b.ToTable("lessons", "content");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.LessonStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_lesson_steps");

                    b.HasIndex("LessonId", "Position")
                        .HasDatabaseName("ix_lesson_steps_lesson_id_position");

                    b.ToTable("lesson_steps", "content");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerKey")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_key");

                    b.Property<Guid>("LessonStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_step_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("LessonStepId")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_lesson_step_id");

                    b.ToTable("questions", "content");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("Grade")
                        .HasDatabaseName("ix_sections_grade");

                    b.ToTable("sections", "content");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.StepMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("LessonStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_step_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_step_materials");

                    b.HasIndex("LessonStepId", "Position")
                        .HasDatabaseName("ix_step_materials_lesson_step_id_position");

                    b.ToTable("step_materials", "content");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.Lesson", b =>
                {
                    b.HasOne("CraftAi.Modules.Content.Domain.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_sections_section_id");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.LessonStep", b =>
                {
                    b.HasOne("CraftAi.Modules.Content.Domain.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_steps_lessons_lesson_id");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.Question", b =>
                {
                    b.HasOne("CraftAi.Modules.Content.Domain.LessonStep", null)
                        .WithMany()
                        .HasForeignKey("LessonStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_lesson_steps_lesson_step_id");
                });

            modelBuilder.Entity("CraftAi.Modules.Content.Domain.StepMaterial", b =>
                {
                    b.HasOne("CraftAi.Modules.Content.Domain.LessonStep", null)
                        .WithMany()
                        .HasForeignKey("LessonStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_step_materials_lesson_steps_lesson_step_id");
                });
#pragma warning restore 612, 618
        }
    }
}
