<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\CraftAi.SharedKernel\CraftAi.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Identity\CraftAi.Modules.Identity.Contracts\CraftAi.Modules.Identity.Contracts.csproj" />
  </ItemGroup>

</Project>
