// <auto-generated />
using System;
using CraftAi.Modules.Pisa.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CraftAi.Modules.Pisa.Persistence.Migrations
{
    [DbContext(typeof(PisaDbContext))]
    [Migration("20260911125426_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pisa")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftAi.Modules.Pisa.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("CognitiveProcess")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cognitive_process");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<int>("ExpectedTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("expected_time_minutes");

                    b.Property<int>("GradeRangeMax")
                        .HasColumnType("integer")
                        .HasColumnName("grade_range_max");

                    b.Property<int>("GradeRangeMin")
                        .HasColumnType("integer")
                        .HasColumnName("grade_range_min");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("Stimulus")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stimulus");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("Direction", "Level")
                        .HasDatabaseName("ix_items_direction_level");

                    b.HasIndex("GradeRangeMin", "GradeRangeMax")
                        .HasDatabaseName("ix_items_grade_range_min_grade_range_max");

                    b.ToTable("items", "pisa");
                });

            modelBuilder.Entity("CraftAi.Modules.Pisa.Domain.ItemQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerKey")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_key");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_item_questions");

                    b.HasIndex("ItemId", "Position")
                        .HasDatabaseName("ix_item_questions_item_id_position");

                    b.ToTable("item_questions", "pisa");
                });

            modelBuilder.Entity("CraftAi.Modules.Pisa.Domain.ItemQuestion", b =>
                {
                    b.HasOne("CraftAi.Modules.Pisa.Domain.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_questions_items_item_id");
                });
#pragma warning restore 612, 618
        }
    }
}
